apiVersion: apps/v1
kind: ReplicaSet
metadata:
   name: rs
   labels:
     app: myapp
spec:
  replicas: 3
  template:
    metadata:
      name: np-pod
      labels:
        app: np-pod #tags
  kind: pod
  spec:
      containers:
        - name: nginx-container
          image: nginx
          ports:
            - containerPort: 80
